version: '3.8'

services:
  mdialer-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ASTERISK_AMI_HOST=${ASTERISK_AMI_HOST:-host.docker.internal}
      - ASTERISK_AMI_PORT=${ASTERISK_AMI_PORT:-5038}
      - ASTERISK_AMI_USERNAME=${ASTERISK_AMI_USERNAME:-admin}
      - ASTERISK_AMI_PASSWORD=${ASTERISK_AMI_PASSWORD:-amp111}
      - API_KEY=${API_KEY:-your-secure-api-key}
      - DEV_API_KEY=${DEV_API_KEY:-dev-api-key}
      - MOCK_TIMEOUT_MINUTES=${MOCK_TIMEOUT_MINUTES:-5}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Include Asterisk container for development
  # asterisk:
  #   image: asterisk:latest
  #   ports:
  #     - "5038:5038"  # AMI port
  #   volumes:
  #     - ./asterisk-config:/etc/asterisk
  #   restart: unless-stopped

volumes:
  logs:

